"""
Invites Router.

This module provides endpoints to fetch, check, mark read, and delete
notifications generated by the IMAP email polling system (Upwork invites, messages, offers).
"""

from typing import List
import uuid
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc, update, delete
from backend.database import get_db
from backend.models import InviteNotification
from backend.schemas import InviteNotificationResponse
from backend.email_monitor import poll_email_invites

router = APIRouter()

@router.get("/", response_model=List[InviteNotificationResponse])
async def get_invites(db: AsyncSession = Depends(get_db)):
    """Fetch the list of latest invite/message notifications."""
    stmt = select(InviteNotification).order_by(desc(InviteNotification.created_at))
    result = await db.execute(stmt)
    invites = result.scalars().all()
    return invites

@router.post("/check-email")
async def check_email_now(db: AsyncSession = Depends(get_db)):
    """Trigger an instant IMAP email poll to check for new Upwork invites & messages."""
    try:
        new_count = await poll_email_invites(db)
        return {"status": "ok", "new_invites_found": new_count}
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Email check failed: {str(e)}"
        )

@router.put("/{invite_id}/read", response_model=InviteNotificationResponse)
async def mark_invite_read(invite_id: uuid.UUID, db: AsyncSession = Depends(get_db)):
    """Mark a specific invite notification as read (notified_web = True)."""
    stmt = select(InviteNotification).where(InviteNotification.id == invite_id)
    res = await db.execute(stmt)
    invite = res.scalar_one_or_none()
    if not invite:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Invite notification not found")
    
    invite.notified_web = True
    await db.commit()
    await db.refresh(invite)
    return invite

@router.put("/read-all")
async def mark_all_invites_read(db: AsyncSession = Depends(get_db)):
    """Mark all invite notifications as read."""
    await db.execute(update(InviteNotification).values(notified_web=True))
    await db.commit()
    return {"status": "ok", "message": "All invites marked as read"}

@router.delete("/{invite_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_invite(invite_id: uuid.UUID, db: AsyncSession = Depends(get_db)):
    """Delete an invite notification."""
    stmt = select(InviteNotification).where(InviteNotification.id == invite_id)
    res = await db.execute(stmt)
    invite = res.scalar_one_or_none()
    if not invite:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Invite notification not found")
    
    await db.delete(invite)
    await db.commit()
    return None
