"""add experience_level column

Revision ID: 15c420f127c6
Revises: b0d10adfda05
Create Date: 2026-08-03 18:16:09.504072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c420f127c6'
down_revision: Union[str, Sequence[str], None] = 'b0d10adfda05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('experience_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'experience_level')
    # ### end Alembic commands ###
